services:
  db:
    image: mysql:5.7
    container_name: wp-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: wp_local
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: wp-password
      MYSQL_ROOT_PASSWORD: root-password

    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - 8000:80
    restart: always
    volumes:
      - wp-data:/var/www/html

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp-user
      WORDPRESS_DB_PASSWORD: wp-password
      WORDPRESS_DB_NAME: wp_local
      WORDPRESS_TABLE_PREFIX: wp_

      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8000');
        define('WP_SITEURL', 'http://localhost:8000');
        define('WP_ENVIRONMENT_TYPE', 'local');

  phpmyadmin:
    user: "${UID:-1000}:${GID:-1000}"
    image: phpmyadmin/phpmyadmin:latest
    environment:
      UPLOAD_LIMIT: 1000M
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80

volumes:
  db_data:
    driver: local

  wp-data:
    driver: local
